### ISSUE TITLE
StreamRecorder release failure

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/HoloLens2ForCV#33] opened 2020-09-27 01:25 UTC
When I use VS compiler release StreamRecorder project VS2019 hint I: MSB3073 StreamRecorder \ StreamRecorderApp \ packages \ Microsoft Windows. CppWinRT. 2.0.200729.8 \ build \ native ....\bin" cppwinRT @"ARM64\Release\cppwinrt_ref.rsp" "retired with code 1.
. In Microsoft Windows. CppWinRT. The targets file of 544 rows

This has caused my project to fail to launch. Can anyone help me?thank you
![image](https://user-images.githubusercontent.com/53859046/94353398-47d8ec80-00a3-11eb-9864-674203d7ebb9.png)

**Comment by fbogo** [comment] 2020-09-28 16:17
Duplicate of #25

**Closed by fbogo** 2020-09-28 16:17 UTC
